// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fmt"

type BrainstormListData struct {
	ProjectID   int64
	ProjectName string
	Chats       []BrainstormChatView
}

type BrainstormChatView struct {
	ID      int64
	Title   string
	Preview string
}

func BrainstormListPage(data BrainstormListData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex-between mb-4\"><h1>")
			if err != nil {
				return err
			}
			var_3 := `Chat`
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1><div><a href=\"")
			if err != nil {
				return err
			}
			var var_4 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d", data.ProjectID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_4)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary\">")
			if err != nil {
				return err
			}
			var_5 := `Back`
			_, err = templBuffer.WriteString(var_5)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a><form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/brainstorm", data.ProjectID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" style=\"display:inline\"><button type=\"submit\" class=\"btn\">")
			if err != nil {
				return err
			}
			var_6 := `New`
			_, err = templBuffer.WriteString(var_6)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></form></div></div> ")
			if err != nil {
				return err
			}
			if len(data.Chats) == 0 {
				_, err = templBuffer.WriteString("<p class=\"text-muted\">")
				if err != nil {
					return err
				}
				var_7 := `No chats yet. Start a new one.`
				_, err = templBuffer.WriteString(var_7)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			for _, chat := range data.Chats {
				_, err = templBuffer.WriteString("<a href=\"")
				if err != nil {
					return err
				}
				var var_8 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/brainstorm/%d", data.ProjectID, chat.ID))
				_, err = templBuffer.WriteString(templ.EscapeString(string(var_8)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" class=\"card\" style=\"text-decoration:none;color:inherit;display:block\"><strong>")
				if err != nil {
					return err
				}
				var var_9 string = chat.Title
				_, err = templBuffer.WriteString(templ.EscapeString(var_9))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</strong>")
				if err != nil {
					return err
				}
				if chat.Preview != "" {
					_, err = templBuffer.WriteString("<p class=\"text-muted\" style=\"margin-top:0.25rem;font-size:0.85rem;line-height:1.3;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden\">")
					if err != nil {
						return err
					}
					var var_10 string = chat.Preview
					_, err = templBuffer.WriteString(templ.EscapeString(var_10))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</p>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("</a>")
				if err != nil {
					return err
				}
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = Layout(data.ProjectName+" - Chat").Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

type BrainstormChatData struct {
	ProjectID   int64
	ProjectName string
	ChatID      int64
	ChatTitle   string
	Messages    []BrainstormMsgView
}

type BrainstormMsgView struct {
	Role     string
	Content  string
	Thinking string
}

func BrainstormChatPage(data BrainstormChatData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_11 := templ.GetChildren(ctx)
		if var_11 == nil {
			var_11 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_12 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex-between mb-4\"><h1>")
			if err != nil {
				return err
			}
			var var_13 string = data.ChatTitle
			_, err = templBuffer.WriteString(templ.EscapeString(var_13))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1><div><a href=\"")
			if err != nil {
				return err
			}
			var var_14 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/brainstorm", data.ProjectID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_14)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary\">")
			if err != nil {
				return err
			}
			var_15 := `Back`
			_, err = templBuffer.WriteString(var_15)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a><form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/brainstorm/%d/push", data.ProjectID, data.ChatID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" style=\"display:inline\"><button type=\"submit\" class=\"btn\">")
			if err != nil {
				return err
			}
			var_16 := `Push to Pipeline`
			_, err = templBuffer.WriteString(var_16)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></form></div></div> <div class=\"chat-messages\" id=\"chat-messages\">")
			if err != nil {
				return err
			}
			for _, msg := range data.Messages {
				var var_17 = []any{"chat-msg chat-msg-" + msg.Role}
				err = templ.RenderCSSItems(ctx, templBuffer, var_17...)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("<div class=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_17).String()))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\"><div class=\"chat-msg-role\">")
				if err != nil {
					return err
				}
				var var_18 string = msg.Role
				_, err = templBuffer.WriteString(templ.EscapeString(var_18))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</div><div style=\"white-space:pre-wrap\">")
				if err != nil {
					return err
				}
				if msg.Thinking != "" {
					_, err = templBuffer.WriteString("<details class=\"thinking-details\"><summary>")
					if err != nil {
						return err
					}
					var_19 := `Thinking (done)`
					_, err = templBuffer.WriteString(var_19)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</summary><pre>")
					if err != nil {
						return err
					}
					var var_20 string = msg.Thinking
					_, err = templBuffer.WriteString(templ.EscapeString(var_20))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</pre></details>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString(" ")
				if err != nil {
					return err
				}
				var var_21 string = msg.Content
				_, err = templBuffer.WriteString(templ.EscapeString(var_21))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</div></div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</div> <form id=\"chat-form\" class=\"mt-2\"><div class=\"form-group\"><textarea id=\"chat-input\" placeholder=\"Type your message... (Cmd+Enter to send)\" style=\"min-height:80px\"></textarea></div><button type=\"submit\" id=\"chat-send\" class=\"btn\">")
			if err != nil {
				return err
			}
			var_22 := `Send`
			_, err = templBuffer.WriteString(var_22)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></form> <script>")
			if err != nil {
				return err
			}
			var_23 := `
			(function() {
				var form = document.getElementById('chat-form');
				var input = document.getElementById('chat-input');
				var btn = document.getElementById('chat-send');
				var messagesEl = document.getElementById('chat-messages');
				var projectID = String(messagesEl.dataset.projectId || '') || location.pathname.split('/')[2];
				var chatID = location.pathname.split('/')[4];

				function scrollToBottom() {
					messagesEl.scrollTop = messagesEl.scrollHeight;
				}

				function addMsg(role, text) {
					var outer = document.createElement('div');
					outer.className = 'chat-msg chat-msg-' + role;
					var roleEl = document.createElement('div');
					roleEl.className = 'chat-msg-role';
					roleEl.textContent = role;
					var bodyEl = document.createElement('div');
					bodyEl.style.whiteSpace = 'pre-wrap';
					bodyEl.textContent = text;
					outer.appendChild(roleEl);
					outer.appendChild(bodyEl);
					messagesEl.appendChild(outer);
					return bodyEl;
				}

				input.addEventListener('keydown', function(e) {
					if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
						e.preventDefault();
						form.dispatchEvent(new Event('submit'));
					}
				});

				form.addEventListener('submit', function(e) {
					e.preventDefault();
					var msg = input.value.trim();
					if (!msg) return;

					input.disabled = true;
					btn.disabled = true;
					btn.textContent = 'Thinking...';
					input.value = '';

					addMsg('user', msg);
					var bodyEl = addMsg('assistant', '');
					var indicator = document.createElement('span');
					indicator.className = 'typing-indicator';
					indicator.textContent = '...';
					bodyEl.textContent = '';
					bodyEl.appendChild(indicator);
					scrollToBottom();

					fetch('/projects/' + projectID + '/brainstorm/' + chatID + '/message', {
						method: 'POST',
						headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
						body: 'content=' + encodeURIComponent(msg)
					}).then(function(res) {
						if (!res.ok) throw new Error('Failed to send');

						var source = new EventSource('/projects/' + projectID + '/brainstorm/' + chatID + '/stream');
						var thinkingEl = null;
						var thinkingPre = null;
						var contentStarted = false;
						var contentNode = document.createTextNode('');
						bodyEl.textContent = '';
						bodyEl.appendChild(contentNode);
						bodyEl.appendChild(indicator);
						source.onmessage = function(event) {
							var d = JSON.parse(event.data);
							if (d.type === 'done') {
								source.close();
								location.reload();
								return;
							}
							if (d.type === 'error') {
								source.close();
								contentNode.textContent += '\nError: ' + d.error;
								if (indicator.parentNode) indicator.remove();
								input.disabled = false;
								btn.disabled = false;
								btn.textContent = 'Send';
								return;
							}
							if (d.type === 'thinking') {
								if (!thinkingEl) {
									if (indicator.parentNode) indicator.remove();
									thinkingEl = document.createElement('details');
									thinkingEl.className = 'thinking-details';
									thinkingEl.setAttribute('open', '');
									var summary = document.createElement('summary');
									summary.textContent = 'Thinking...';
									thinkingEl.appendChild(summary);
									thinkingPre = document.createElement('pre');
									thinkingEl.appendChild(thinkingPre);
									bodyEl.insertBefore(thinkingEl, contentNode);
								}
								thinkingPre.textContent += d.chunk;
								thinkingPre.scrollTop = thinkingPre.scrollHeight;
								scrollToBottom();
							}
							if (d.type === 'chunk') {
								if (!contentStarted && thinkingEl) {
									thinkingEl.removeAttribute('open');
									thinkingEl.querySelector('summary').textContent = 'Thinking (done)';
									contentStarted = true;
								}
								if (!contentStarted) { if (indicator.parentNode) indicator.remove(); contentStarted = true; }
								contentNode.textContent += d.chunk;
								scrollToBottom();
							}
							if (d.type === 'tool_start') {
								if (!contentStarted && thinkingEl) {
									thinkingEl.removeAttribute('open');
									thinkingEl.querySelector('summary').textContent = 'Thinking (done)';
									contentStarted = true;
								}
								contentNode.textContent += '\n[' + d.summary + '...]\n';
								scrollToBottom();
							}
						};
						source.onerror = function() {
							source.close();
							if (indicator.parentNode) indicator.remove();
							input.disabled = false;
							btn.disabled = false;
							btn.textContent = 'Send';
						};
					}).catch(function(err) {
						bodyEl.textContent = 'Error: ' + err.message;
						input.disabled = false;
						btn.disabled = false;
						btn.textContent = 'Send';
					});
				});

				scrollToBottom();
			})();
		`
			_, err = templBuffer.WriteString(var_23)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</script>")
			if err != nil {
				return err
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = Layout(data.ChatTitle).Render(templ.WithChildren(ctx, var_12), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
