// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fmt"

type BrainstormListData struct {
	ProjectID   int64
	ProjectName string
	Chats       []BrainstormChatView
}

type BrainstormChatView struct {
	ID    int64
	Title string
}

func BrainstormListPage(data BrainstormListData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex-between mb-4\"><h1>")
			if err != nil {
				return err
			}
			var_3 := `Brainstorm`
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1><div><a href=\"")
			if err != nil {
				return err
			}
			var var_4 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d", data.ProjectID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_4)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary\">")
			if err != nil {
				return err
			}
			var_5 := `Back`
			_, err = templBuffer.WriteString(var_5)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a><form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/brainstorm", data.ProjectID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" style=\"display:inline\"><input type=\"text\" name=\"title\" placeholder=\"Chat title...\" style=\"width:200px;display:inline\" required><button type=\"submit\" class=\"btn\">")
			if err != nil {
				return err
			}
			var_6 := `New Chat`
			_, err = templBuffer.WriteString(var_6)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></form></div></div> ")
			if err != nil {
				return err
			}
			if len(data.Chats) == 0 {
				_, err = templBuffer.WriteString("<p class=\"text-muted\">")
				if err != nil {
					return err
				}
				var_7 := `No brainstorm chats yet.`
				_, err = templBuffer.WriteString(var_7)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			for _, chat := range data.Chats {
				_, err = templBuffer.WriteString("<a href=\"")
				if err != nil {
					return err
				}
				var var_8 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/brainstorm/%d", data.ProjectID, chat.ID))
				_, err = templBuffer.WriteString(templ.EscapeString(string(var_8)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" class=\"card\" style=\"text-decoration:none;color:inherit;display:block\"><strong>")
				if err != nil {
					return err
				}
				var var_9 string = chat.Title
				_, err = templBuffer.WriteString(templ.EscapeString(var_9))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</strong></a>")
				if err != nil {
					return err
				}
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = Layout(data.ProjectName+" - Brainstorm").Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

type BrainstormChatData struct {
	ProjectID   int64
	ProjectName string
	ChatID      int64
	ChatTitle   string
	Messages    []BrainstormMsgView
}

type BrainstormMsgView struct {
	Role    string
	Content string
}

func BrainstormChatPage(data BrainstormChatData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_10 := templ.GetChildren(ctx)
		if var_10 == nil {
			var_10 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_11 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex-between mb-4\"><h1>")
			if err != nil {
				return err
			}
			var var_12 string = data.ChatTitle
			_, err = templBuffer.WriteString(templ.EscapeString(var_12))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1><div><a href=\"")
			if err != nil {
				return err
			}
			var var_13 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/brainstorm", data.ProjectID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_13)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary\">")
			if err != nil {
				return err
			}
			var_14 := `Back`
			_, err = templBuffer.WriteString(var_14)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a><form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/brainstorm/%d/push", data.ProjectID, data.ChatID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" style=\"display:inline\"><input type=\"text\" name=\"topic\" placeholder=\"Topic to push...\" style=\"width:200px;display:inline\"><button type=\"submit\" class=\"btn\">")
			if err != nil {
				return err
			}
			var_15 := `Push to Pipeline`
			_, err = templBuffer.WriteString(var_15)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></form></div></div> <div class=\"chat-messages\">")
			if err != nil {
				return err
			}
			for _, msg := range data.Messages {
				var var_16 = []any{"chat-msg chat-msg-" + msg.Role}
				err = templ.RenderCSSItems(ctx, templBuffer, var_16...)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("<div class=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_16).String()))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\"><div class=\"chat-msg-role\">")
				if err != nil {
					return err
				}
				var var_17 string = msg.Role
				_, err = templBuffer.WriteString(templ.EscapeString(var_17))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</div><div style=\"white-space:pre-wrap\">")
				if err != nil {
					return err
				}
				var var_18 string = msg.Content
				_, err = templBuffer.WriteString(templ.EscapeString(var_18))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</div></div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</div> <form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/brainstorm/%d/message", data.ProjectID, data.ChatID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\"><div class=\"form-group\"><textarea name=\"content\" placeholder=\"Type your message...\" style=\"min-height:80px\"></textarea></div><button type=\"submit\" class=\"btn\">")
			if err != nil {
				return err
			}
			var_19 := `Send`
			_, err = templBuffer.WriteString(var_19)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></form>")
			if err != nil {
				return err
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = Layout(data.ChatTitle).Render(templ.WithChildren(ctx, var_11), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
