// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"fmt"
	"github.com/zanfridau/marketminded/web/templates/components"
)

func Dashboard(projects []DashboardProject) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex items-center justify-between mb-6\"><h1 class=\"text-2xl font-bold\">")
			if err != nil {
				return err
			}
			var_3 := `Projects`
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1><a href=\"/projects/new\" class=\"btn btn-primary\">")
			if err != nil {
				return err
			}
			var_4 := `New Project`
			_, err = templBuffer.WriteString(var_4)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></div> ")
			if err != nil {
				return err
			}
			if len(projects) == 0 {
				_, err = templBuffer.WriteString("<p class=\"text-base-content/60\">")
				if err != nil {
					return err
				}
				var_5 := `No projects yet. Create one to get started.`
				_, err = templBuffer.WriteString(var_5)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4\">")
			if err != nil {
				return err
			}
			for _, p := range projects {
				_, err = templBuffer.WriteString("<a href=\"")
				if err != nil {
					return err
				}
				var var_6 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d", p.ID))
				_, err = templBuffer.WriteString(templ.EscapeString(string(var_6)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" class=\"card bg-base-100 shadow-sm border border-base-300 hover:border-primary transition-colors no-underline text-inherit\"><div class=\"card-body\"><h3 class=\"card-title text-base\">")
				if err != nil {
					return err
				}
				var var_7 string = p.Name
				_, err = templBuffer.WriteString(templ.EscapeString(var_7))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</h3><p class=\"text-base-content/60\">")
				if err != nil {
					return err
				}
				var var_8 string = p.Description
				_, err = templBuffer.WriteString(templ.EscapeString(var_8))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p></div></a>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</div>")
			if err != nil {
				return err
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = components.PageShell("Dashboard", []components.Breadcrumb{{Label: "Projects"}}).Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

type DashboardProject struct {
	ID          int64
	Name        string
	Description string
}
