// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fmt"

type KnowledgePageData struct {
	ProjectID   int64
	ProjectName string
	Items       []KnowledgeItemView
	HasVoice    bool
	HasTone     bool
}

type KnowledgeItemView struct {
	ID        int64
	Type      string
	Title     string
	Content   string
	SourceURL string
}

func KnowledgePage(data KnowledgePageData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex-between mb-4\"><h1>")
			if err != nil {
				return err
			}
			var_3 := `Knowledge Base`
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1><a href=\"")
			if err != nil {
				return err
			}
			var var_4 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d", data.ProjectID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_4)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary\">")
			if err != nil {
				return err
			}
			var_5 := `Back to Project`
			_, err = templBuffer.WriteString(var_5)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></div> <div class=\"card mb-4\"><h3>")
			if err != nil {
				return err
			}
			var_6 := `Profiles`
			_, err = templBuffer.WriteString(var_6)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h3><p class=\"mb-1\">")
			if err != nil {
				return err
			}
			var_7 := `Voice Profile:`
			_, err = templBuffer.WriteString(var_7)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			if data.HasVoice {
				_, err = templBuffer.WriteString("<span class=\"badge badge-approved\">")
				if err != nil {
					return err
				}
				var_8 := `Built`
				_, err = templBuffer.WriteString(var_8)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span>")
				if err != nil {
					return err
				}
			} else {
				_, err = templBuffer.WriteString("<span class=\"badge badge-draft\">")
				if err != nil {
					return err
				}
				var_9 := `Not built`
				_, err = templBuffer.WriteString(var_9)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			var_10 := `Tone Profile:`
			_, err = templBuffer.WriteString(var_10)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			if data.HasTone {
				_, err = templBuffer.WriteString("<span class=\"badge badge-approved\">")
				if err != nil {
					return err
				}
				var_11 := `Built`
				_, err = templBuffer.WriteString(var_11)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span>")
				if err != nil {
					return err
				}
			} else {
				_, err = templBuffer.WriteString("<span class=\"badge badge-draft\">")
				if err != nil {
					return err
				}
				var_12 := `Not built`
				_, err = templBuffer.WriteString(var_12)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</p><form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/knowledge/build-profiles", data.ProjectID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"mt-2\"><button type=\"submit\" class=\"btn\">")
			if err != nil {
				return err
			}
			var_13 := `Build / Rebuild Profiles`
			_, err = templBuffer.WriteString(var_13)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></form></div> <div class=\"card mb-4\"><h3>")
			if err != nil {
				return err
			}
			var_14 := `Add Knowledge Item`
			_, err = templBuffer.WriteString(var_14)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h3><form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/knowledge", data.ProjectID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\"><div class=\"form-group\"><label for=\"type\">")
			if err != nil {
				return err
			}
			var_15 := `Type`
			_, err = templBuffer.WriteString(var_15)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</label><select id=\"type\" name=\"type\"><option value=\"voice_sample\">")
			if err != nil {
				return err
			}
			var_16 := `Voice Sample`
			_, err = templBuffer.WriteString(var_16)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</option><option value=\"tone_guide\">")
			if err != nil {
				return err
			}
			var_17 := `Tone Guide`
			_, err = templBuffer.WriteString(var_17)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</option><option value=\"brand_doc\">")
			if err != nil {
				return err
			}
			var_18 := `Brand Document`
			_, err = templBuffer.WriteString(var_18)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</option><option value=\"reference\">")
			if err != nil {
				return err
			}
			var_19 := `Reference`
			_, err = templBuffer.WriteString(var_19)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</option></select></div><div class=\"form-group\"><label for=\"title\">")
			if err != nil {
				return err
			}
			var_20 := `Title`
			_, err = templBuffer.WriteString(var_20)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</label><input type=\"text\" id=\"title\" name=\"title\" placeholder=\"Brief title\"></div><div class=\"form-group\"><label for=\"content\">")
			if err != nil {
				return err
			}
			var_21 := `Content`
			_, err = templBuffer.WriteString(var_21)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</label><textarea id=\"content\" name=\"content\" required placeholder=\"Paste content here...\"></textarea></div><div class=\"form-group\"><label for=\"source_url\">")
			if err != nil {
				return err
			}
			var_22 := `Source URL (optional)`
			_, err = templBuffer.WriteString(var_22)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</label><input type=\"url\" id=\"source_url\" name=\"source_url\" placeholder=\"https://...\"></div><button type=\"submit\" class=\"btn\">")
			if err != nil {
				return err
			}
			var_23 := `Add Item`
			_, err = templBuffer.WriteString(var_23)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></form></div> <h2>")
			if err != nil {
				return err
			}
			var_24 := `Items (`
			_, err = templBuffer.WriteString(var_24)
			if err != nil {
				return err
			}
			var var_25 string = fmt.Sprintf("%d", len(data.Items))
			_, err = templBuffer.WriteString(templ.EscapeString(var_25))
			if err != nil {
				return err
			}
			var_26 := `)`
			_, err = templBuffer.WriteString(var_26)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h2> ")
			if err != nil {
				return err
			}
			if len(data.Items) == 0 {
				_, err = templBuffer.WriteString("<p class=\"text-muted\">")
				if err != nil {
					return err
				}
				var_27 := `No knowledge items yet.`
				_, err = templBuffer.WriteString(var_27)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			for _, item := range data.Items {
				_, err = templBuffer.WriteString("<div class=\"card\"><div class=\"flex-between mb-1\"><div><span class=\"badge badge-ideating\">")
				if err != nil {
					return err
				}
				var var_28 string = item.Type
				_, err = templBuffer.WriteString(templ.EscapeString(var_28))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span><strong>")
				if err != nil {
					return err
				}
				var var_29 string = item.Title
				_, err = templBuffer.WriteString(templ.EscapeString(var_29))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</strong></div><form method=\"POST\" action=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/knowledge/%d/delete", data.ProjectID, item.ID))))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\"><button type=\"submit\" class=\"btn btn-danger\" style=\"font-size:0.75rem;padding:0.25rem 0.5rem\">")
				if err != nil {
					return err
				}
				var_30 := `Delete`
				_, err = templBuffer.WriteString(var_30)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></form></div><p class=\"text-muted\" style=\"white-space:pre-wrap;max-height:100px;overflow:hidden\">")
				if err != nil {
					return err
				}
				var var_31 string = item.Content
				_, err = templBuffer.WriteString(templ.EscapeString(var_31))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p></div>")
				if err != nil {
					return err
				}
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = Layout(data.ProjectName+" - Knowledge").Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
