// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fmt"

type PipelineListData struct {
	ProjectID   int64
	ProjectName string
	Runs        []PipelineRunView
}

type PipelineRunView struct {
	ID     int64
	Status string
	Topic  string
}

func PipelineListPage(data PipelineListData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex-between mb-4\"><h1>")
			if err != nil {
				return err
			}
			var_3 := `Pipeline Runs`
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1><div><a href=\"")
			if err != nil {
				return err
			}
			var var_4 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d", data.ProjectID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_4)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary\">")
			if err != nil {
				return err
			}
			var_5 := `Back`
			_, err = templBuffer.WriteString(var_5)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a><form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline", data.ProjectID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" style=\"display:inline\"><button type=\"submit\" class=\"btn\">")
			if err != nil {
				return err
			}
			var_6 := `New Run`
			_, err = templBuffer.WriteString(var_6)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></form></div></div> ")
			if err != nil {
				return err
			}
			if len(data.Runs) == 0 {
				_, err = templBuffer.WriteString("<p class=\"text-muted\">")
				if err != nil {
					return err
				}
				var_7 := `No pipeline runs yet. Start one to generate content.`
				_, err = templBuffer.WriteString(var_7)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			for _, run := range data.Runs {
				_, err = templBuffer.WriteString("<a href=\"")
				if err != nil {
					return err
				}
				var var_8 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline/%d", data.ProjectID, run.ID))
				_, err = templBuffer.WriteString(templ.EscapeString(string(var_8)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" class=\"card\" style=\"text-decoration:none;color:inherit;display:block\"><div class=\"flex-between\"><div><strong>")
				if err != nil {
					return err
				}
				var_9 := `Run #`
				_, err = templBuffer.WriteString(var_9)
				if err != nil {
					return err
				}
				var var_10 string = fmt.Sprintf("%d", run.ID)
				_, err = templBuffer.WriteString(templ.EscapeString(var_10))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</strong>")
				if err != nil {
					return err
				}
				if run.Topic != "" {
					_, err = templBuffer.WriteString("<span class=\"text-muted\">")
					if err != nil {
						return err
					}
					var_11 := `— `
					_, err = templBuffer.WriteString(var_11)
					if err != nil {
						return err
					}
					var var_12 string = run.Topic
					_, err = templBuffer.WriteString(templ.EscapeString(var_12))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</span>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("</div>")
				if err != nil {
					return err
				}
				var var_13 = []any{"badge badge-" + run.Status}
				err = templ.RenderCSSItems(ctx, templBuffer, var_13...)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("<span class=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_13).String()))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\">")
				if err != nil {
					return err
				}
				var var_14 string = run.Status
				_, err = templBuffer.WriteString(templ.EscapeString(var_14))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span></div></a>")
				if err != nil {
					return err
				}
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = Layout(data.ProjectName+" - Pipeline").Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

type PipelineRunData struct {
	ProjectID   int64
	ProjectName string
	RunID       int64
	Status      string
	Topic       string
	Content     []ContentPieceView
}

type ContentPieceView struct {
	ID     int64
	Type   string
	Title  string
	Body   string
	Status string
}

func PipelineRunPage(data PipelineRunData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_15 := templ.GetChildren(ctx)
		if var_15 == nil {
			var_15 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_16 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex-between mb-4\"><h1>")
			if err != nil {
				return err
			}
			var_17 := `Pipeline Run #`
			_, err = templBuffer.WriteString(var_17)
			if err != nil {
				return err
			}
			var var_18 string = fmt.Sprintf("%d", data.RunID)
			_, err = templBuffer.WriteString(templ.EscapeString(var_18))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1><div>")
			if err != nil {
				return err
			}
			var var_19 = []any{"badge badge-" + data.Status}
			err = templ.RenderCSSItems(ctx, templBuffer, var_19...)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("<span class=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_19).String()))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\">")
			if err != nil {
				return err
			}
			var var_20 string = data.Status
			_, err = templBuffer.WriteString(templ.EscapeString(var_20))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</span><a href=\"")
			if err != nil {
				return err
			}
			var var_21 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline", data.ProjectID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_21)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary\" style=\"margin-left:0.5rem\">")
			if err != nil {
				return err
			}
			var_22 := `Back`
			_, err = templBuffer.WriteString(var_22)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></div></div> ")
			if err != nil {
				return err
			}
			if data.Status == "ideating" {
				_, err = templBuffer.WriteString("<div class=\"card\" x-data=\"streamOutput\"><h3 class=\"mb-2\">")
				if err != nil {
					return err
				}
				var_23 := `Stage 1: Ideation`
				_, err = templBuffer.WriteString(var_23)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</h3><p class=\"text-muted mb-2\">")
				if err != nil {
					return err
				}
				var_24 := `AI will research trends and suggest pillar topics.`
				_, err = templBuffer.WriteString(var_24)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p><button class=\"btn mb-2\" @click=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("startStream('/projects/%d/pipeline/%d/stream/ideate')", data.ProjectID, data.RunID)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" x-show=\"!loading\">")
				if err != nil {
					return err
				}
				var_25 := `Generate Ideas`
				_, err = templBuffer.WriteString(var_25)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button><p x-show=\"loading\" class=\"text-muted\">")
				if err != nil {
					return err
				}
				var_26 := `Generating...`
				_, err = templBuffer.WriteString(var_26)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p><div class=\"stream-output\" x-show=\"content\" x-text=\"content\"></div><p x-show=\"error\" style=\"color:red\" x-text=\"error\"></p><form method=\"POST\" action=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline/%d/advance", data.ProjectID, data.RunID))))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" x-show=\"content &amp;&amp; !loading\" class=\"mt-2\"><input type=\"hidden\" name=\"next_status\" value=\"creating_pillar\"><div class=\"form-group\"><label>")
				if err != nil {
					return err
				}
				var_27 := `Selected Topic`
				_, err = templBuffer.WriteString(var_27)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</label><input type=\"text\" name=\"topic\" required placeholder=\"Type or paste the topic you chose\"></div><button type=\"submit\" class=\"btn\">")
				if err != nil {
					return err
				}
				var_28 := `Select Topic &amp; Continue`
				_, err = templBuffer.WriteString(var_28)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></form></div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			if data.Status == "creating_pillar" {
				_, err = templBuffer.WriteString("<div class=\"card\" x-data=\"streamOutput\"><h3 class=\"mb-2\">")
				if err != nil {
					return err
				}
				var_29 := `Stage 2: Create Pillar`
				_, err = templBuffer.WriteString(var_29)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</h3><p class=\"text-muted mb-2\">")
				if err != nil {
					return err
				}
				var_30 := `Topic: `
				_, err = templBuffer.WriteString(var_30)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("<strong>")
				if err != nil {
					return err
				}
				var var_31 string = data.Topic
				_, err = templBuffer.WriteString(templ.EscapeString(var_31))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</strong></p><button class=\"btn mb-2\" @click=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("startStream('/projects/%d/pipeline/%d/stream/pillar')", data.ProjectID, data.RunID)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" x-show=\"!loading\">")
				if err != nil {
					return err
				}
				var_32 := `Generate Blog Post`
				_, err = templBuffer.WriteString(var_32)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button><p x-show=\"loading\" class=\"text-muted\">")
				if err != nil {
					return err
				}
				var_33 := `Writing...`
				_, err = templBuffer.WriteString(var_33)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p><div class=\"stream-output\" x-show=\"content\" x-text=\"content\"></div><p x-show=\"error\" style=\"color:red\" x-text=\"error\"></p><form method=\"POST\" action=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline/%d/advance", data.ProjectID, data.RunID))))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" x-show=\"content &amp;&amp; !loading\" class=\"mt-2\"><input type=\"hidden\" name=\"next_status\" value=\"waterfalling\"><button type=\"submit\" class=\"btn\">")
				if err != nil {
					return err
				}
				var_34 := `Approve &amp; Continue to Waterfall`
				_, err = templBuffer.WriteString(var_34)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></form></div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			if data.Status == "waterfalling" {
				_, err = templBuffer.WriteString("<div class=\"card\" x-data=\"streamOutput\"><h3 class=\"mb-2\">")
				if err != nil {
					return err
				}
				var_35 := `Stage 3: Content Waterfall`
				_, err = templBuffer.WriteString(var_35)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</h3><p class=\"text-muted mb-2\">")
				if err != nil {
					return err
				}
				var_36 := `Generating social posts from pillar content.`
				_, err = templBuffer.WriteString(var_36)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p><button class=\"btn mb-2\" @click=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("startStream('/projects/%d/pipeline/%d/stream/waterfall')", data.ProjectID, data.RunID)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" x-show=\"!loading\">")
				if err != nil {
					return err
				}
				var_37 := `Generate Social Posts`
				_, err = templBuffer.WriteString(var_37)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button><p x-show=\"loading\" class=\"text-muted\">")
				if err != nil {
					return err
				}
				var_38 := `Creating...`
				_, err = templBuffer.WriteString(var_38)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p><div class=\"stream-output\" x-show=\"content\" x-text=\"content\"></div><p x-show=\"error\" style=\"color:red\" x-text=\"error\"></p><form method=\"POST\" action=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline/%d/advance", data.ProjectID, data.RunID))))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" x-show=\"content &amp;&amp; !loading\" class=\"mt-2\"><input type=\"hidden\" name=\"next_status\" value=\"complete\"><button type=\"submit\" class=\"btn\">")
				if err != nil {
					return err
				}
				var_39 := `Mark Complete`
				_, err = templBuffer.WriteString(var_39)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></form></div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			if data.Status == "complete" || data.Status == "abandoned" {
				_, err = templBuffer.WriteString("<div class=\"card\"><h3 class=\"mb-2\">")
				if err != nil {
					return err
				}
				var_40 := `Pipeline `
				_, err = templBuffer.WriteString(var_40)
				if err != nil {
					return err
				}
				var var_41 string = data.Status
				_, err = templBuffer.WriteString(templ.EscapeString(var_41))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</h3>")
				if err != nil {
					return err
				}
				if data.Topic != "" {
					_, err = templBuffer.WriteString("<p class=\"text-muted mb-2\">")
					if err != nil {
						return err
					}
					var_42 := `Topic: `
					_, err = templBuffer.WriteString(var_42)
					if err != nil {
						return err
					}
					var var_43 string = data.Topic
					_, err = templBuffer.WriteString(templ.EscapeString(var_43))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</p>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("</div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			if len(data.Content) > 0 {
				_, err = templBuffer.WriteString("<h2 class=\"mt-2 mb-2\">")
				if err != nil {
					return err
				}
				var_44 := `Generated Content`
				_, err = templBuffer.WriteString(var_44)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</h2> ")
				if err != nil {
					return err
				}
				for _, piece := range data.Content {
					_, err = templBuffer.WriteString("<div class=\"card\"><div class=\"flex-between mb-1\"><div><span class=\"badge badge-ideating\">")
					if err != nil {
						return err
					}
					var var_45 string = piece.Type
					_, err = templBuffer.WriteString(templ.EscapeString(var_45))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</span><strong>")
					if err != nil {
						return err
					}
					var var_46 string = piece.Title
					_, err = templBuffer.WriteString(templ.EscapeString(var_46))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</strong></div>")
					if err != nil {
						return err
					}
					var var_47 = []any{"badge badge-" + piece.Status}
					err = templ.RenderCSSItems(ctx, templBuffer, var_47...)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("<span class=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_47).String()))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\">")
					if err != nil {
						return err
					}
					var var_48 string = piece.Status
					_, err = templBuffer.WriteString(templ.EscapeString(var_48))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</span></div><p style=\"white-space:pre-wrap;max-height:200px;overflow:auto\" class=\"text-muted\">")
					if err != nil {
						return err
					}
					var var_49 string = piece.Body
					_, err = templBuffer.WriteString(templ.EscapeString(var_49))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</p><div class=\"mt-2\"><a href=\"")
					if err != nil {
						return err
					}
					var var_50 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/content/%d", data.ProjectID, piece.ID))
					_, err = templBuffer.WriteString(templ.EscapeString(string(var_50)))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\" class=\"btn btn-secondary\" style=\"font-size:0.75rem\">")
					if err != nil {
						return err
					}
					var_51 := `Edit`
					_, err = templBuffer.WriteString(var_51)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</a></div></div>")
					if err != nil {
						return err
					}
				}
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			if data.Status != "complete" && data.Status != "abandoned" {
				_, err = templBuffer.WriteString("<form method=\"POST\" action=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline/%d/abandon", data.ProjectID, data.RunID))))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" class=\"mt-2\"><button type=\"submit\" class=\"btn btn-danger\">")
				if err != nil {
					return err
				}
				var_52 := `Abandon Run`
				_, err = templBuffer.WriteString(var_52)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></form>")
				if err != nil {
					return err
				}
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = Layout(fmt.Sprintf("Run #%d", data.RunID)).Render(templ.WithChildren(ctx, var_16), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
