// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fmt"

type PipelineListData struct {
	ProjectID   int64
	ProjectName string
	Runs        []PipelineRunView
}

type PipelineRunView struct {
	ID     int64
	Status string
	Topic  string
}

func PipelineListPage(data PipelineListData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex-between mb-4\"><h1>")
			if err != nil {
				return err
			}
			var_3 := `Pipeline Runs`
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1><a href=\"")
			if err != nil {
				return err
			}
			var var_4 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d", data.ProjectID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_4)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary\">")
			if err != nil {
				return err
			}
			var_5 := `Back`
			_, err = templBuffer.WriteString(var_5)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></div> <form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline", data.ProjectID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"card mb-2\"><div class=\"form-group\"><label>")
			if err != nil {
				return err
			}
			var_6 := `Topic`
			_, err = templBuffer.WriteString(var_6)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</label><input type=\"text\" name=\"topic\" required placeholder=\"What should the content be about?\"></div><button type=\"submit\" class=\"btn\">")
			if err != nil {
				return err
			}
			var_7 := `Start New Run`
			_, err = templBuffer.WriteString(var_7)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></form> ")
			if err != nil {
				return err
			}
			if len(data.Runs) == 0 {
				_, err = templBuffer.WriteString("<p class=\"text-muted\">")
				if err != nil {
					return err
				}
				var_8 := `No pipeline runs yet. Enter a topic above to start.`
				_, err = templBuffer.WriteString(var_8)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			for _, run := range data.Runs {
				_, err = templBuffer.WriteString("<a href=\"")
				if err != nil {
					return err
				}
				var var_9 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline/%d", data.ProjectID, run.ID))
				_, err = templBuffer.WriteString(templ.EscapeString(string(var_9)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" class=\"card\" style=\"text-decoration:none;color:inherit;display:block\"><div class=\"flex-between\"><div><strong>")
				if err != nil {
					return err
				}
				var var_10 string = run.Topic
				_, err = templBuffer.WriteString(templ.EscapeString(var_10))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</strong></div>")
				if err != nil {
					return err
				}
				var var_11 = []any{"badge badge-" + run.Status}
				err = templ.RenderCSSItems(ctx, templBuffer, var_11...)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("<span class=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_11).String()))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\">")
				if err != nil {
					return err
				}
				var var_12 string = run.Status
				_, err = templBuffer.WriteString(templ.EscapeString(var_12))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span></div></a>")
				if err != nil {
					return err
				}
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = Layout(data.ProjectName+" - Pipeline").Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

type ProductionBoardData struct {
	ProjectID   int64
	ProjectName string
	RunID       int64
	Topic       string
	Plan        string
	Status      string
	Pieces      []ContentPieceView
	NextPieceID int64
}

type ContentPieceView struct {
	ID              int64
	Platform        string
	Format          string
	Title           string
	Body            string
	Status          string
	SortOrder       int
	RejectionReason string
	IsCornerstone   bool
}

type ContentEditData struct {
	ProjectID int64
	Piece     ContentPieceView
}

func ProductionBoardPage(data ProductionBoardData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_13 := templ.GetChildren(ctx)
		if var_13 == nil {
			var_13 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_14 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div id=\"production-board\" data-project-id=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", data.ProjectID)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" data-run-id=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", data.RunID)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" data-next-piece-id=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", data.NextPieceID)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\"><div class=\"board-header flex-between mb-4\"><div><h1>")
			if err != nil {
				return err
			}
			var var_15 string = data.Topic
			_, err = templBuffer.WriteString(templ.EscapeString(var_15))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1>")
			if err != nil {
				return err
			}
			var var_16 = []any{"badge badge-" + data.Status}
			err = templ.RenderCSSItems(ctx, templBuffer, var_16...)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("<span class=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_16).String()))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\">")
			if err != nil {
				return err
			}
			var var_17 string = data.Status
			_, err = templBuffer.WriteString(templ.EscapeString(var_17))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</span></div><div><a href=\"")
			if err != nil {
				return err
			}
			var var_18 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline", data.ProjectID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_18)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary\">")
			if err != nil {
				return err
			}
			var_19 := `Back`
			_, err = templBuffer.WriteString(var_19)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a>")
			if err != nil {
				return err
			}
			if data.Status != "complete" && data.Status != "abandoned" {
				_, err = templBuffer.WriteString("<form method=\"POST\" action=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline/%d/abandon", data.ProjectID, data.RunID))))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" style=\"display:inline\"><button type=\"submit\" class=\"btn btn-danger\" style=\"margin-left:0.5rem\">")
				if err != nil {
					return err
				}
				var_20 := `Abandon`
				_, err = templBuffer.WriteString(var_20)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></form>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</div></div>")
			if err != nil {
				return err
			}
			if data.Status == "planning" {
				_, err = templBuffer.WriteString("<div class=\"board-card\" id=\"plan-card\"><div class=\"board-card-header\"><h3>")
				if err != nil {
					return err
				}
				var_21 := `Production Plan`
				_, err = templBuffer.WriteString(var_21)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</h3><span class=\"badge badge-planning\">")
				if err != nil {
					return err
				}
				var_22 := `planning`
				_, err = templBuffer.WriteString(var_22)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span></div>")
				if err != nil {
					return err
				}
				if data.Plan != "" {
					_, err = templBuffer.WriteString("<div class=\"board-card-body\" id=\"plan-body\">")
					if err != nil {
						return err
					}
					var var_23 string = data.Plan
					_, err = templBuffer.WriteString(templ.EscapeString(var_23))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</div> <div class=\"board-card-actions\"><form method=\"POST\" action=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline/%d/approve-plan", data.ProjectID, data.RunID))))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\" style=\"display:inline\"><button type=\"submit\" class=\"btn\">")
					if err != nil {
						return err
					}
					var_24 := `Approve Plan`
					_, err = templBuffer.WriteString(var_24)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button></form><form method=\"POST\" action=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline/%d/reject-plan", data.ProjectID, data.RunID))))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\" style=\"display:inline\"><input type=\"text\" name=\"reason\" placeholder=\"Rejection reason (optional)\" style=\"width:auto;display:inline;margin:0\"><button type=\"submit\" class=\"btn btn-secondary\">")
					if err != nil {
						return err
					}
					var_25 := `Reject &amp; Re-plan`
					_, err = templBuffer.WriteString(var_25)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button></form></div>")
					if err != nil {
						return err
					}
				} else {
					_, err = templBuffer.WriteString("<div class=\"board-card-body\" id=\"plan-body\"><p class=\"text-muted\">")
					if err != nil {
						return err
					}
					var_26 := `Click Generate to create a production plan.`
					_, err = templBuffer.WriteString(var_26)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</p></div> <div class=\"board-card-actions\"><button class=\"btn\" id=\"generate-plan-btn\">")
					if err != nil {
						return err
					}
					var_27 := `Generate Plan`
					_, err = templBuffer.WriteString(var_27)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button></div>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("</div>")
				if err != nil {
					return err
				}
			}
			if data.Status == "producing" || data.Status == "complete" || data.Status == "abandoned" {
				if data.Plan != "" {
					_, err = templBuffer.WriteString("<div class=\"board-card\"><div class=\"board-card-header\"><h3>")
					if err != nil {
						return err
					}
					var_28 := `Production Plan`
					_, err = templBuffer.WriteString(var_28)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</h3>")
					if err != nil {
						return err
					}
					var var_29 = []any{"badge badge-" + data.Status}
					err = templ.RenderCSSItems(ctx, templBuffer, var_29...)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("<span class=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_29).String()))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\">")
					if err != nil {
						return err
					}
					var var_30 string = data.Status
					_, err = templBuffer.WriteString(templ.EscapeString(var_30))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</span></div><div class=\"board-card-body collapsed\" id=\"plan-body\">")
					if err != nil {
						return err
					}
					var var_31 string = data.Plan
					_, err = templBuffer.WriteString(templ.EscapeString(var_31))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</div></div>")
					if err != nil {
						return err
					}
				}
			}
			for _, piece := range data.Pieces {
				var var_32 = []any{"board-card",
					templ.KV("board-card-cornerstone", piece.IsCornerstone),
					templ.KV("board-card-pending", piece.Status == "pending"),
					templ.KV("board-card-generating", piece.Status == "generating"),
					templ.KV("board-card-draft", piece.Status == "draft"),
					templ.KV("board-card-approved", piece.Status == "approved"),
					templ.KV("board-card-rejected", piece.Status == "rejected"),
				}
				err = templ.RenderCSSItems(ctx, templBuffer, var_32...)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("<div class=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_32).String()))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" data-piece-id=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", piece.ID)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\"><div class=\"board-card-header\"><div><span class=\"badge badge-planning\">")
				if err != nil {
					return err
				}
				var var_33 string = piece.Platform
				_, err = templBuffer.WriteString(templ.EscapeString(var_33))
				if err != nil {
					return err
				}
				var_34 := `/`
				_, err = templBuffer.WriteString(var_34)
				if err != nil {
					return err
				}
				var var_35 string = piece.Format
				_, err = templBuffer.WriteString(templ.EscapeString(var_35))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span>")
				if err != nil {
					return err
				}
				if piece.IsCornerstone {
					_, err = templBuffer.WriteString("<span class=\"badge badge-approved\" style=\"margin-left:0.25rem\">")
					if err != nil {
						return err
					}
					var_36 := `cornerstone`
					_, err = templBuffer.WriteString(var_36)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</span>")
					if err != nil {
						return err
					}
				}
				if piece.Title != "" {
					_, err = templBuffer.WriteString("<strong style=\"margin-left:0.5rem\">")
					if err != nil {
						return err
					}
					var var_37 string = piece.Title
					_, err = templBuffer.WriteString(templ.EscapeString(var_37))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</strong>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("</div>")
				if err != nil {
					return err
				}
				var var_38 = []any{"badge badge-" + piece.Status}
				err = templ.RenderCSSItems(ctx, templBuffer, var_38...)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("<span class=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_38).String()))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\">")
				if err != nil {
					return err
				}
				var var_39 string = piece.Status
				_, err = templBuffer.WriteString(templ.EscapeString(var_39))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span></div>")
				if err != nil {
					return err
				}
				var var_40 = []any{"board-card-body", templ.KV("collapsed", piece.Status == "approved")}
				err = templ.RenderCSSItems(ctx, templBuffer, var_40...)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("<div class=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_40).String()))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" id=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("piece-body-%d", piece.ID)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" data-platform=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(piece.Platform))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" data-format=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(piece.Format))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\">")
				if err != nil {
					return err
				}
				if piece.Body != "" {
					var var_41 string = piece.Body
					_, err = templBuffer.WriteString(templ.EscapeString(var_41))
					if err != nil {
						return err
					}
				} else if piece.Status == "pending" {
					_, err = templBuffer.WriteString("<p class=\"text-muted\">")
					if err != nil {
						return err
					}
					var_42 := `Waiting to be generated...`
					_, err = templBuffer.WriteString(var_42)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</p>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("</div>")
				if err != nil {
					return err
				}
				if piece.RejectionReason != "" && piece.Status == "rejected" {
					_, err = templBuffer.WriteString("<p style=\"color:#dc2626;font-size:0.85rem;margin-bottom:0.5rem\">")
					if err != nil {
						return err
					}
					var_43 := `Rejected: `
					_, err = templBuffer.WriteString(var_43)
					if err != nil {
						return err
					}
					var var_44 string = piece.RejectionReason
					_, err = templBuffer.WriteString(templ.EscapeString(var_44))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</p>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("<div class=\"board-card-actions\" id=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("piece-actions-%d", piece.ID)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\">")
				if err != nil {
					return err
				}
				if piece.ID == data.NextPieceID && (piece.Status == "pending" || piece.Status == "rejected") {
					_, err = templBuffer.WriteString("<button class=\"btn piece-generate-btn\" data-piece-id=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", piece.ID)))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\">")
					if err != nil {
						return err
					}
					var_45 := `Generate`
					_, err = templBuffer.WriteString(var_45)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button>")
					if err != nil {
						return err
					}
				}
				if piece.Status == "generating" {
					_, err = templBuffer.WriteString("<form method=\"POST\" action=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline/%d/piece/%d/abort", data.ProjectID, data.RunID, piece.ID))))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\" style=\"display:inline\"><button type=\"submit\" class=\"btn btn-danger\">")
					if err != nil {
						return err
					}
					var_46 := `Abort`
					_, err = templBuffer.WriteString(var_46)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button></form>")
					if err != nil {
						return err
					}
				}
				if piece.Status == "draft" {
					_, err = templBuffer.WriteString("<button class=\"btn piece-approve-btn\" data-piece-id=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", piece.ID)))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\">")
					if err != nil {
						return err
					}
					var_47 := `Approve`
					_, err = templBuffer.WriteString(var_47)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button> <button class=\"btn btn-danger piece-reject-btn\" data-piece-id=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", piece.ID)))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\">")
					if err != nil {
						return err
					}
					var_48 := `Reject`
					_, err = templBuffer.WriteString(var_48)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button> <button class=\"btn btn-secondary piece-improve-btn\" data-piece-id=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", piece.ID)))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\">")
					if err != nil {
						return err
					}
					var_49 := `Improve`
					_, err = templBuffer.WriteString(var_49)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button> <form method=\"POST\" action=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline/%d/piece/%d/proofread", data.ProjectID, data.RunID, piece.ID))))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\" style=\"display:inline\"><button type=\"submit\" class=\"btn btn-secondary\">")
					if err != nil {
						return err
					}
					var_50 := `Proofread`
					_, err = templBuffer.WriteString(var_50)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button></form>")
					if err != nil {
						return err
					}
				}
				if piece.Status == "approved" {
					_, err = templBuffer.WriteString("<button class=\"btn btn-secondary piece-improve-btn\" data-piece-id=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", piece.ID)))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\">")
					if err != nil {
						return err
					}
					var_51 := `Improve`
					_, err = templBuffer.WriteString(var_51)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button> <form method=\"POST\" action=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline/%d/piece/%d/proofread", data.ProjectID, data.RunID, piece.ID))))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\" style=\"display:inline\"><button type=\"submit\" class=\"btn btn-secondary\">")
					if err != nil {
						return err
					}
					var_52 := `Proofread`
					_, err = templBuffer.WriteString(var_52)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button></form>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("</div><div class=\"improve-chat\" id=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("improve-chat-%d", piece.ID)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" style=\"display:none\"><div class=\"improve-chat-messages\" id=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("improve-messages-%d", piece.ID)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\"></div><form class=\"improve-form\" data-piece-id=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", piece.ID)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\"><textarea placeholder=\"What should be improved?\" style=\"min-height:60px\" name=\"content\"></textarea><button type=\"submit\" class=\"btn\" style=\"margin-top:0.25rem\">")
				if err != nil {
					return err
				}
				var_53 := `Send &amp; Rewrite`
				_, err = templBuffer.WriteString(var_53)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></form></div></div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</div>")
			if err != nil {
				return err
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = Layout(fmt.Sprintf("Pipeline: %s", data.Topic)).Render(templ.WithChildren(ctx, var_14), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

func ContentEditPage(data ContentEditData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_54 := templ.GetChildren(ctx)
		if var_54 == nil {
			var_54 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_55 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex-between mb-4\"><h1>")
			if err != nil {
				return err
			}
			var_56 := `Edit Content`
			_, err = templBuffer.WriteString(var_56)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1><a href=\"")
			if err != nil {
				return err
			}
			var var_57 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline", data.ProjectID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_57)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary\">")
			if err != nil {
				return err
			}
			var_58 := `Back`
			_, err = templBuffer.WriteString(var_58)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></div> <div class=\"card\"><div class=\"flex-between mb-2\"><span class=\"badge badge-planning\">")
			if err != nil {
				return err
			}
			var var_59 string = data.Piece.Platform
			_, err = templBuffer.WriteString(templ.EscapeString(var_59))
			if err != nil {
				return err
			}
			var_60 := `/`
			_, err = templBuffer.WriteString(var_60)
			if err != nil {
				return err
			}
			var var_61 string = data.Piece.Format
			_, err = templBuffer.WriteString(templ.EscapeString(var_61))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</span>")
			if err != nil {
				return err
			}
			var var_62 = []any{"badge badge-" + data.Piece.Status}
			err = templ.RenderCSSItems(ctx, templBuffer, var_62...)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("<span class=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_62).String()))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\">")
			if err != nil {
				return err
			}
			var var_63 string = data.Piece.Status
			_, err = templBuffer.WriteString(templ.EscapeString(var_63))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</span></div><form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/content/%d", data.ProjectID, data.Piece.ID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\"><div class=\"form-group\"><label>")
			if err != nil {
				return err
			}
			var_64 := `Title`
			_, err = templBuffer.WriteString(var_64)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</label><input type=\"text\" name=\"title\" value=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(data.Piece.Title))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\"></div><div class=\"form-group\"><label>")
			if err != nil {
				return err
			}
			var_65 := `Body`
			_, err = templBuffer.WriteString(var_65)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</label><textarea name=\"body\" style=\"min-height:400px\">")
			if err != nil {
				return err
			}
			var var_66 string = data.Piece.Body
			_, err = templBuffer.WriteString(templ.EscapeString(var_66))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</textarea></div><button type=\"submit\" class=\"btn\">")
			if err != nil {
				return err
			}
			var_67 := `Save`
			_, err = templBuffer.WriteString(var_67)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button>")
			if err != nil {
				return err
			}
			if data.Piece.Status == "draft" {
				_, err = templBuffer.WriteString("<button type=\"submit\" name=\"action\" value=\"approve\" class=\"btn\" style=\"margin-left:0.5rem;background:#059669\">")
				if err != nil {
					return err
				}
				var_68 := `Approve`
				_, err = templBuffer.WriteString(var_68)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</form></div>")
			if err != nil {
				return err
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = Layout("Edit Content").Render(templ.WithChildren(ctx, var_55), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
