// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/zanfridau/marketminded/web/templates/components"

func ProjectNew() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<h1 class=\"text-xl font-semibold text-zinc-100 mb-8\">")
			if err != nil {
				return err
			}
			var_3 := `New Project`
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1> <form method=\"POST\" action=\"/projects\">")
			if err != nil {
				return err
			}
			var_4 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
				templBuffer, templIsBuffer := w.(*bytes.Buffer)
				if !templIsBuffer {
					templBuffer = templ.GetBuffer()
					defer templ.ReleaseBuffer(templBuffer)
				}
				var_5 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
					templBuffer, templIsBuffer := w.(*bytes.Buffer)
					if !templIsBuffer {
						templBuffer = templ.GetBuffer()
						defer templ.ReleaseBuffer(templBuffer)
					}
					_, err = templBuffer.WriteString("<input type=\"text\" id=\"name\" name=\"name\" required placeholder=\"e.g. Acme Corp\" class=\"input\">")
					if err != nil {
						return err
					}
					if !templIsBuffer {
						_, err = io.Copy(w, templBuffer)
					}
					return err
				})
				err = components.FormGroup("Project Name").Render(templ.WithChildren(ctx, var_5), templBuffer)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(" ")
				if err != nil {
					return err
				}
				var_6 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
					templBuffer, templIsBuffer := w.(*bytes.Buffer)
					if !templIsBuffer {
						templBuffer = templ.GetBuffer()
						defer templ.ReleaseBuffer(templBuffer)
					}
					_, err = templBuffer.WriteString("<textarea id=\"description\" name=\"description\" placeholder=\"Brief description of the client/project\" class=\"textarea\"></textarea>")
					if err != nil {
						return err
					}
					if !templIsBuffer {
						_, err = io.Copy(w, templBuffer)
					}
					return err
				})
				err = components.FormGroup("Description").Render(templ.WithChildren(ctx, var_6), templBuffer)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(" <div class=\"mt-4\">")
				if err != nil {
					return err
				}
				err = components.SubmitButton("Create Project").Render(ctx, templBuffer)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</div>")
				if err != nil {
					return err
				}
				if !templIsBuffer {
					_, err = io.Copy(w, templBuffer)
				}
				return err
			})
			err = components.Card("").Render(templ.WithChildren(ctx, var_4), templBuffer)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</form>")
			if err != nil {
				return err
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = components.PageShell("New Project", []components.Breadcrumb{{Label: "Projects", URL: "/"}, {Label: "New Project"}}).Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
