// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fmt"
import "github.com/zanfridau/marketminded/web/templates/components"

type ProjectDetail struct {
	ID          int64
	Name        string
	Description string
	HasProfile  bool
	RunCount    int
	Language    string
	HasContext  bool
	HasMemory   bool
}

func ProjectOverview(p ProjectDetail) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex items-center justify-between mb-6\"><h1 class=\"text-2xl font-bold\">")
			if err != nil {
				return err
			}
			var var_3 string = p.Name
			_, err = templBuffer.WriteString(templ.EscapeString(var_3))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1></div> ")
			if err != nil {
				return err
			}
			if p.Description != "" {
				_, err = templBuffer.WriteString("<p class=\"text-base-content/60 mb-6\">")
				if err != nil {
					return err
				}
				var var_4 string = p.Description
				_, err = templBuffer.WriteString(templ.EscapeString(var_4))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4\"><div class=\"card bg-base-100 shadow-sm border border-base-300\"><div class=\"card-body p-4\"><h3 class=\"font-semibold text-base\">")
			if err != nil {
				return err
			}
			var_5 := `Client Profile`
			_, err = templBuffer.WriteString(var_5)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h3><p class=\"mb-2\">")
			if err != nil {
				return err
			}
			if p.HasProfile {
				err = components.StatusBadge("approved").Render(ctx, templBuffer)
				if err != nil {
					return err
				}
			} else {
				err = components.StatusBadge("draft").Render(ctx, templBuffer)
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</p><a href=\"")
			if err != nil {
				return err
			}
			var var_6 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/profile", p.ID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_6)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary btn-sm\">")
			if err != nil {
				return err
			}
			var_7 := `Manage Profile`
			_, err = templBuffer.WriteString(var_7)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></div></div><div class=\"card bg-base-100 shadow-sm border border-base-300\"><div class=\"card-body p-4\"><h3 class=\"font-semibold text-base\">")
			if err != nil {
				return err
			}
			var_8 := `Context & Memories`
			_, err = templBuffer.WriteString(var_8)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h3><p class=\"mb-2\">")
			if err != nil {
				return err
			}
			if p.HasContext || p.HasMemory {
				err = components.StatusBadge("approved").Render(ctx, templBuffer)
				if err != nil {
					return err
				}
			} else {
				err = components.StatusBadge("draft").Render(ctx, templBuffer)
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</p><a href=\"")
			if err != nil {
				return err
			}
			var var_9 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/context-memory", p.ID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_9)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary btn-sm\">")
			if err != nil {
				return err
			}
			var_10 := `Manage`
			_, err = templBuffer.WriteString(var_10)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></div></div><div class=\"card bg-base-100 shadow-sm border border-base-300\"><div class=\"card-body p-4\"><h3 class=\"font-semibold text-base\">")
			if err != nil {
				return err
			}
			var_11 := `Settings`
			_, err = templBuffer.WriteString(var_11)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h3><p class=\"mb-2\">")
			if err != nil {
				return err
			}
			if p.Language != "" {
				var_12 := `Language: `
				_, err = templBuffer.WriteString(var_12)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("<strong>")
				if err != nil {
					return err
				}
				var var_13 string = p.Language
				_, err = templBuffer.WriteString(templ.EscapeString(var_13))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</strong>")
				if err != nil {
					return err
				}
			} else {
				err = components.StatusBadge("draft").Render(ctx, templBuffer)
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</p><a href=\"")
			if err != nil {
				return err
			}
			var var_14 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/settings", p.ID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_14)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary btn-sm\">")
			if err != nil {
				return err
			}
			var_15 := `Manage Settings`
			_, err = templBuffer.WriteString(var_15)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></div></div><div class=\"card bg-base-100 shadow-sm border border-base-300\"><div class=\"card-body p-4\"><h3 class=\"font-semibold text-base\">")
			if err != nil {
				return err
			}
			var_16 := `Content Pipeline`
			_, err = templBuffer.WriteString(var_16)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h3><p class=\"mb-2 text-base-content/60\">")
			if err != nil {
				return err
			}
			var var_17 string = fmt.Sprintf("%d pipeline runs", p.RunCount)
			_, err = templBuffer.WriteString(templ.EscapeString(var_17))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</p><a href=\"")
			if err != nil {
				return err
			}
			var var_18 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/pipeline", p.ID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_18)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary btn-sm\">")
			if err != nil {
				return err
			}
			var_19 := `Pipeline Runs`
			_, err = templBuffer.WriteString(var_19)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></div></div></div>")
			if err != nil {
				return err
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = components.ProjectPageShell(p.Name, []components.Breadcrumb{{Label: "Projects", URL: "/"}, {Label: p.Name}}, p.ID).Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
