// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fmt"

type TemplatesMgrData struct {
	ProjectID   int64
	ProjectName string
	Templates   []TemplateMgrView
}

type TemplateMgrView struct {
	ID          int64
	Name        string
	Platform    string
	HTMLContent string
}

func TemplatesMgrPage(data TemplatesMgrData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex-between mb-4\"><h1>")
			if err != nil {
				return err
			}
			var_3 := `Social Post Templates`
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1><a href=\"")
			if err != nil {
				return err
			}
			var var_4 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d", data.ProjectID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_4)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-secondary\">")
			if err != nil {
				return err
			}
			var_5 := `Back`
			_, err = templBuffer.WriteString(var_5)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></div> <div class=\"card mb-4\"><h3>")
			if err != nil {
				return err
			}
			var_6 := `Add Template`
			_, err = templBuffer.WriteString(var_6)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h3><p class=\"text-muted mb-2\">")
			if err != nil {
				return err
			}
			var_7 := `HTML templates must include `
			_, err = templBuffer.WriteString(var_7)
			if err != nil {
				return err
			}
			var var_8 string = "{{.Title}}"
			_, err = templBuffer.WriteString(templ.EscapeString(var_8))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			var_9 := `and `
			_, err = templBuffer.WriteString(var_9)
			if err != nil {
				return err
			}
			var var_10 string = "{{.Body}}"
			_, err = templBuffer.WriteString(templ.EscapeString(var_10))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			var_11 := `slots. Optional: `
			_, err = templBuffer.WriteString(var_11)
			if err != nil {
				return err
			}
			var var_12 string = "{{.ImageURL}}"
			_, err = templBuffer.WriteString(templ.EscapeString(var_12))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</p><form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/templates", data.ProjectID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\"><div class=\"form-group\"><label>")
			if err != nil {
				return err
			}
			var_13 := `Name`
			_, err = templBuffer.WriteString(var_13)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</label><input type=\"text\" name=\"name\" required placeholder=\"e.g. Instagram Square\"></div><div class=\"form-group\"><label>")
			if err != nil {
				return err
			}
			var_14 := `Platform`
			_, err = templBuffer.WriteString(var_14)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</label><select name=\"platform\"><option value=\"instagram\">")
			if err != nil {
				return err
			}
			var_15 := `Instagram`
			_, err = templBuffer.WriteString(var_15)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</option><option value=\"facebook\">")
			if err != nil {
				return err
			}
			var_16 := `Facebook`
			_, err = templBuffer.WriteString(var_16)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</option><option value=\"linkedin\">")
			if err != nil {
				return err
			}
			var_17 := `LinkedIn`
			_, err = templBuffer.WriteString(var_17)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</option></select></div><div class=\"form-group\"><label>")
			if err != nil {
				return err
			}
			var_18 := `HTML Content`
			_, err = templBuffer.WriteString(var_18)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</label><textarea name=\"html_content\" required style=\"font-family:monospace\" placeholder=\"&lt;div&gt;{{.Title}}&lt;/div&gt;\"></textarea></div><button type=\"submit\" class=\"btn\">")
			if err != nil {
				return err
			}
			var_19 := `Add Template`
			_, err = templBuffer.WriteString(var_19)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></form></div> <h2 class=\"mb-2\">")
			if err != nil {
				return err
			}
			var_20 := `Templates (`
			_, err = templBuffer.WriteString(var_20)
			if err != nil {
				return err
			}
			var var_21 string = fmt.Sprintf("%d", len(data.Templates))
			_, err = templBuffer.WriteString(templ.EscapeString(var_21))
			if err != nil {
				return err
			}
			var_22 := `)`
			_, err = templBuffer.WriteString(var_22)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h2> ")
			if err != nil {
				return err
			}
			for _, tmpl := range data.Templates {
				_, err = templBuffer.WriteString("<div class=\"card\"><div class=\"flex-between mb-1\"><div><span class=\"badge badge-ideating\">")
				if err != nil {
					return err
				}
				var var_23 string = tmpl.Platform
				_, err = templBuffer.WriteString(templ.EscapeString(var_23))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span><strong>")
				if err != nil {
					return err
				}
				var var_24 string = tmpl.Name
				_, err = templBuffer.WriteString(templ.EscapeString(var_24))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</strong></div><form method=\"POST\" action=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/templates/%d/delete", data.ProjectID, tmpl.ID))))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\"><button type=\"submit\" class=\"btn btn-danger\" style=\"font-size:0.75rem;padding:0.25rem 0.5rem\">")
				if err != nil {
					return err
				}
				var_25 := `Delete`
				_, err = templBuffer.WriteString(var_25)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></form></div><pre style=\"background:#f9f9f9;padding:0.5rem;border-radius:4px;font-size:0.75rem;overflow:auto;max-height:100px\">")
				if err != nil {
					return err
				}
				var var_26 string = tmpl.HTMLContent
				_, err = templBuffer.WriteString(templ.EscapeString(var_26))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</pre></div>")
				if err != nil {
					return err
				}
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = Layout(data.ProjectName+" - Templates").Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
