// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"fmt"
	"github.com/zanfridau/marketminded/web/templates/components"
)

type TemplatesMgrData struct {
	ProjectID   int64
	ProjectName string
	Templates   []TemplateMgrView
}

type TemplateMgrView struct {
	ID          int64
	Name        string
	Platform    string
	HTMLContent string
}

func TemplatesMgrPage(data TemplatesMgrData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"card bg-base-100 shadow-sm border border-base-300 mb-6\"><div class=\"card-body\"><h3 class=\"card-title text-base\">")
			if err != nil {
				return err
			}
			var_3 := `Add Template`
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h3><p class=\"text-base-content/60 text-sm mb-3\">")
			if err != nil {
				return err
			}
			var_4 := `HTML templates must include `
			_, err = templBuffer.WriteString(var_4)
			if err != nil {
				return err
			}
			var var_5 string = "{{.Title}}"
			_, err = templBuffer.WriteString(templ.EscapeString(var_5))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			var_6 := `and `
			_, err = templBuffer.WriteString(var_6)
			if err != nil {
				return err
			}
			var var_7 string = "{{.Body}}"
			_, err = templBuffer.WriteString(templ.EscapeString(var_7))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			var_8 := `slots. Optional: `
			_, err = templBuffer.WriteString(var_8)
			if err != nil {
				return err
			}
			var var_9 string = "{{.ImageURL}}"
			_, err = templBuffer.WriteString(templ.EscapeString(var_9))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</p><form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/templates", data.ProjectID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\">")
			if err != nil {
				return err
			}
			var_10 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
				templBuffer, templIsBuffer := w.(*bytes.Buffer)
				if !templIsBuffer {
					templBuffer = templ.GetBuffer()
					defer templ.ReleaseBuffer(templBuffer)
				}
				_, err = templBuffer.WriteString("<input type=\"text\" name=\"name\" required placeholder=\"e.g. Instagram Square\" class=\"input input-bordered w-full\">")
				if err != nil {
					return err
				}
				if !templIsBuffer {
					_, err = io.Copy(w, templBuffer)
				}
				return err
			})
			err = components.FormGroup("Name").Render(templ.WithChildren(ctx, var_10), templBuffer)
			if err != nil {
				return err
			}
			var_11 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
				templBuffer, templIsBuffer := w.(*bytes.Buffer)
				if !templIsBuffer {
					templBuffer = templ.GetBuffer()
					defer templ.ReleaseBuffer(templBuffer)
				}
				_, err = templBuffer.WriteString("<select name=\"platform\" class=\"select select-bordered w-full\"><option value=\"instagram\">")
				if err != nil {
					return err
				}
				var_12 := `Instagram`
				_, err = templBuffer.WriteString(var_12)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</option><option value=\"facebook\">")
				if err != nil {
					return err
				}
				var_13 := `Facebook`
				_, err = templBuffer.WriteString(var_13)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</option><option value=\"linkedin\">")
				if err != nil {
					return err
				}
				var_14 := `LinkedIn`
				_, err = templBuffer.WriteString(var_14)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</option></select>")
				if err != nil {
					return err
				}
				if !templIsBuffer {
					_, err = io.Copy(w, templBuffer)
				}
				return err
			})
			err = components.FormGroup("Platform").Render(templ.WithChildren(ctx, var_11), templBuffer)
			if err != nil {
				return err
			}
			var_15 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
				templBuffer, templIsBuffer := w.(*bytes.Buffer)
				if !templIsBuffer {
					templBuffer = templ.GetBuffer()
					defer templ.ReleaseBuffer(templBuffer)
				}
				_, err = templBuffer.WriteString("<textarea name=\"html_content\" required placeholder=\"&lt;div&gt;{{.Title}}&lt;/div&gt;\" class=\"textarea textarea-bordered w-full font-mono\"></textarea>")
				if err != nil {
					return err
				}
				if !templIsBuffer {
					_, err = io.Copy(w, templBuffer)
				}
				return err
			})
			err = components.FormGroup("HTML Content").Render(templ.WithChildren(ctx, var_15), templBuffer)
			if err != nil {
				return err
			}
			err = components.SubmitButton("Add Template").Render(ctx, templBuffer)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</form></div></div> <h2 class=\"text-xl font-bold mb-3\">")
			if err != nil {
				return err
			}
			var_16 := `Templates (`
			_, err = templBuffer.WriteString(var_16)
			if err != nil {
				return err
			}
			var var_17 string = fmt.Sprintf("%d", len(data.Templates))
			_, err = templBuffer.WriteString(templ.EscapeString(var_17))
			if err != nil {
				return err
			}
			var_18 := `)`
			_, err = templBuffer.WriteString(var_18)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h2> ")
			if err != nil {
				return err
			}
			for _, tmpl := range data.Templates {
				_, err = templBuffer.WriteString("<div class=\"card bg-base-100 shadow-sm border border-base-300 mb-2\"><div class=\"card-body\"><div class=\"flex items-center justify-between\"><div class=\"flex items-center gap-2\"><span class=\"badge badge-ghost\">")
				if err != nil {
					return err
				}
				var var_19 string = tmpl.Platform
				_, err = templBuffer.WriteString(templ.EscapeString(var_19))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span><strong>")
				if err != nil {
					return err
				}
				var var_20 string = tmpl.Name
				_, err = templBuffer.WriteString(templ.EscapeString(var_20))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</strong></div><form method=\"POST\" action=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/templates/%d/delete", data.ProjectID, tmpl.ID))))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\"><button type=\"submit\" class=\"btn btn-error btn-xs\">")
				if err != nil {
					return err
				}
				var_21 := `Delete`
				_, err = templBuffer.WriteString(var_21)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></form></div><pre class=\"bg-base-200 p-3 rounded-lg text-xs overflow-auto max-h-24\">")
				if err != nil {
					return err
				}
				var var_22 string = tmpl.HTMLContent
				_, err = templBuffer.WriteString(templ.EscapeString(var_22))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</pre></div></div>")
				if err != nil {
					return err
				}
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = components.ProjectPageShell(data.ProjectName+" - Templates", []components.Breadcrumb{
			{Label: "Projects", URL: "/projects"},
			{Label: data.ProjectName, URL: fmt.Sprintf("/projects/%d", data.ProjectID)},
			{Label: "Templates"},
		}, data.ProjectID).Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
