// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"fmt"
	"github.com/zanfridau/marketminded/web/templates/components"
	"time"
)

type TopicListData struct {
	ProjectID   int64
	ProjectName string
	Runs        []TopicRunView
	Backlog     []TopicBacklogView
}

type TopicRunView struct {
	ID         int64
	Status     string
	TopicCount int
	CreatedAt  time.Time
}

type TopicBacklogView struct {
	ID     int64
	Title  string
	Angle  string
	Status string
}

type TopicRunData struct {
	ProjectID      int64
	ProjectName    string
	RunID          int64
	Status         string
	Instructions   string
	Steps          []TopicStepView
	ApprovedTopics []TopicBacklogView
}

type TopicStepView struct {
	ID        int64
	StepType  string
	Round     int
	Status    string
	Output    string
	Thinking  string
	ToolCalls string
	Usage     string
}

func topicStepTypeLabel(stepType string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		switch stepType {
		case "topic_explore":
			var_2 := `Explorer`
			_, err = templBuffer.WriteString(var_2)
			if err != nil {
				return err
			}
		case "topic_review":
			var_3 := `Reviewer`
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
		default:
			var var_4 string = stepType
			_, err = templBuffer.WriteString(templ.EscapeString(var_4))
			if err != nil {
				return err
			}
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

func TopicListPage(data TopicListData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_5 := templ.GetChildren(ctx)
		if var_5 == nil {
			var_5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_6 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div class=\"flex items-center justify-between mb-6\"><h1 class=\"text-2xl font-bold\">")
			if err != nil {
				return err
			}
			var_7 := `Topics`
			_, err = templBuffer.WriteString(var_7)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1></div> <div class=\"card p-4 mb-6\"><form method=\"POST\" action=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/topics/generate", data.ProjectID))))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\"><label class=\"text-sm font-medium text-zinc-300 mb-2 block\">")
			if err != nil {
				return err
			}
			var_8 := `Extra Instructions (optional)`
			_, err = templBuffer.WriteString(var_8)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</label><textarea name=\"instructions\" class=\"textarea w-full min-h-[60px] mb-3\" placeholder=\"e.g. Focus on AI regulation news, or Look at what competitors are writing about, or I want something about sustainability...\"></textarea><button type=\"submit\" class=\"btn btn-primary btn-sm\">")
			if err != nil {
				return err
			}
			var_9 := `Generate Topics`
			_, err = templBuffer.WriteString(var_9)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></form></div> ")
			if err != nil {
				return err
			}
			if len(data.Backlog) > 0 {
				_, err = templBuffer.WriteString("<h2 class=\"text-lg font-semibold text-zinc-300 mb-3\">")
				if err != nil {
					return err
				}
				var_10 := `Topic Backlog`
				_, err = templBuffer.WriteString(var_10)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</h2> <div class=\"grid grid-cols-1 md:grid-cols-2 gap-3 mb-8\">")
				if err != nil {
					return err
				}
				for _, item := range data.Backlog {
					var var_11 = []any{"card p-4", templ.KV("opacity-50", item.Status == "used")}
					err = templ.RenderCSSItems(ctx, templBuffer, var_11...)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("<div class=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(templ.CSSClasses(var_11).String()))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\"><div class=\"flex items-start justify-between gap-2\"><div class=\"min-w-0\"><h3 class=\"font-semibold text-zinc-100 text-sm\">")
					if err != nil {
						return err
					}
					var var_12 string = item.Title
					_, err = templBuffer.WriteString(templ.EscapeString(var_12))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</h3><p class=\"text-zinc-400 text-xs mt-1 line-clamp-3\">")
					if err != nil {
						return err
					}
					var var_13 string = item.Angle
					_, err = templBuffer.WriteString(templ.EscapeString(var_13))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</p></div>")
					if err != nil {
						return err
					}
					if item.Status == "used" {
						_, err = templBuffer.WriteString("<span class=\"badge badge-sm badge-ghost shrink-0\">")
						if err != nil {
							return err
						}
						var_14 := `Used`
						_, err = templBuffer.WriteString(var_14)
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString("</span>")
						if err != nil {
							return err
						}
					}
					_, err = templBuffer.WriteString("</div>")
					if err != nil {
						return err
					}
					if item.Status == "available" {
						_, err = templBuffer.WriteString("<div class=\"flex gap-2 mt-3\"><form method=\"POST\" action=\"")
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/topics/backlog/%d/start", data.ProjectID, item.ID))))
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString("\" class=\"inline\"><button type=\"submit\" class=\"btn btn-primary btn-xs\">")
						if err != nil {
							return err
						}
						var_15 := `Start Pipeline`
						_, err = templBuffer.WriteString(var_15)
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString("</button></form><form method=\"POST\" action=\"")
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/topics/backlog/%d/delete", data.ProjectID, item.ID))))
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString("\" class=\"inline\" onsubmit=\"return confirm(&#39;Delete this topic?&#39;)\"><button type=\"submit\" class=\"btn btn-ghost btn-xs text-red-400\">")
						if err != nil {
							return err
						}
						var_16 := `Delete`
						_, err = templBuffer.WriteString(var_16)
						if err != nil {
							return err
						}
						_, err = templBuffer.WriteString("</button></form></div>")
						if err != nil {
							return err
						}
					}
					_, err = templBuffer.WriteString("</div>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("</div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString(" <h2 class=\"text-lg font-semibold text-zinc-300 mb-3\">")
			if err != nil {
				return err
			}
			var_17 := `Generation Runs`
			_, err = templBuffer.WriteString(var_17)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h2> <div class=\"flex flex-col gap-3\">")
			if err != nil {
				return err
			}
			if len(data.Runs) == 0 {
				_, err = templBuffer.WriteString("<p class=\"text-zinc-500\">")
				if err != nil {
					return err
				}
				var_18 := `No topic generation runs yet. Click Generate to start.`
				_, err = templBuffer.WriteString(var_18)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p>")
				if err != nil {
					return err
				}
			}
			for _, run := range data.Runs {
				_, err = templBuffer.WriteString("<div class=\"card hover:border-zinc-700 transition-colors\"><div class=\"p-4 flex items-center justify-between\"><a href=\"")
				if err != nil {
					return err
				}
				var var_19 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/topics/%d", data.ProjectID, run.ID))
				_, err = templBuffer.WriteString(templ.EscapeString(string(var_19)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" class=\"flex items-center gap-3 flex-1\"><span class=\"text-sm text-zinc-400\">")
				if err != nil {
					return err
				}
				var var_20 string = run.CreatedAt.Format("Jan 2, 2006 3:04 PM")
				_, err = templBuffer.WriteString(templ.EscapeString(var_20))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</span>")
				if err != nil {
					return err
				}
				if run.TopicCount > 0 {
					_, err = templBuffer.WriteString("<span class=\"text-xs text-zinc-500\">")
					if err != nil {
						return err
					}
					var var_21 string = fmt.Sprintf("%d topics", run.TopicCount)
					_, err = templBuffer.WriteString(templ.EscapeString(var_21))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</span>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("</a><div class=\"flex items-center gap-3\">")
				if err != nil {
					return err
				}
				err = components.StatusBadge(run.Status).Render(ctx, templBuffer)
				if err != nil {
					return err
				}
				if run.Status == "running" {
					_, err = templBuffer.WriteString("<form method=\"POST\" action=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/topics/%d/cancel", data.ProjectID, run.ID))))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\"><button type=\"submit\" class=\"text-zinc-500 hover:text-red-400 transition-colors text-sm\">")
					if err != nil {
						return err
					}
					var_22 := `Cancel`
					_, err = templBuffer.WriteString(var_22)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button></form>")
					if err != nil {
						return err
					}
				}
				if run.Status == "completed" || run.Status == "failed" {
					_, err = templBuffer.WriteString("<form method=\"POST\" action=\"")
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/topics/%d/delete", data.ProjectID, run.ID))))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("\" onsubmit=\"return confirm(&#39;Delete this run?&#39;)\"><button type=\"submit\" class=\"text-zinc-500 hover:text-red-400 transition-colors text-sm\">")
					if err != nil {
						return err
					}
					var_23 := `Delete`
					_, err = templBuffer.WriteString(var_23)
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</button></form>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("</div></div></div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</div>")
			if err != nil {
				return err
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = components.ProjectPageShell(data.ProjectName+" - Topics", []components.Breadcrumb{
			{Label: "Projects", URL: "/projects"},
			{Label: data.ProjectName, URL: fmt.Sprintf("/projects/%d", data.ProjectID)},
			{Label: "Topics"},
		}, data.ProjectID, data.ProjectName, "topics").Render(templ.WithChildren(ctx, var_6), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}

func TopicRunPage(data TopicRunData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_24 := templ.GetChildren(ctx)
		if var_24 == nil {
			var_24 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_25 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<div id=\"topic-run-page\" data-project-id=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", data.ProjectID)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" data-run-id=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", data.RunID)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" data-status=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(data.Status))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\"><div class=\"flex items-center justify-between mb-4\"><div>")
			if err != nil {
				return err
			}
			err = components.StatusBadge(data.Status).Render(ctx, templBuffer)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("<h1 class=\"text-2xl font-bold mt-1\">")
			if err != nil {
				return err
			}
			var_26 := `Topic Generation`
			_, err = templBuffer.WriteString(var_26)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1></div><div class=\"flex items-center gap-2\">")
			if err != nil {
				return err
			}
			if data.Status == "completed" || data.Status == "failed" {
				_, err = templBuffer.WriteString("<form method=\"POST\" action=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/topics/%d/delete", data.ProjectID, data.RunID))))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" onsubmit=\"return confirm(&#39;Delete this run?&#39;)\"><button type=\"submit\" class=\"btn btn-danger btn-sm\">")
				if err != nil {
					return err
				}
				var_27 := `Delete`
				_, err = templBuffer.WriteString(var_27)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></form>")
				if err != nil {
					return err
				}
			}
			if data.Status == "running" {
				_, err = templBuffer.WriteString("<form method=\"POST\" action=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/topics/%d/cancel", data.ProjectID, data.RunID))))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" onsubmit=\"return confirm(&#39;Cancel this run?&#39;)\"><button type=\"submit\" class=\"btn btn-danger btn-sm\">")
				if err != nil {
					return err
				}
				var_28 := `Cancel`
				_, err = templBuffer.WriteString(var_28)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></form>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("<a href=\"")
			if err != nil {
				return err
			}
			var var_29 templ.SafeURL = templ.SafeURL(fmt.Sprintf("/projects/%d/topics", data.ProjectID))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_29)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"btn btn-ghost btn-sm\">")
			if err != nil {
				return err
			}
			var_30 := `Back`
			_, err = templBuffer.WriteString(var_30)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></div></div>")
			if err != nil {
				return err
			}
			if data.Instructions != "" {
				_, err = templBuffer.WriteString("<div class=\"card p-3 mb-4\"><p class=\"text-xs font-medium text-zinc-500 mb-1\">")
				if err != nil {
					return err
				}
				var_31 := `Instructions`
				_, err = templBuffer.WriteString(var_31)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p><p class=\"text-sm text-zinc-300\">")
				if err != nil {
					return err
				}
				var var_32 string = data.Instructions
				_, err = templBuffer.WriteString(templ.EscapeString(var_32))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</p></div>")
				if err != nil {
					return err
				}
			}
			if len(data.ApprovedTopics) > 0 {
				_, err = templBuffer.WriteString("<h2 class=\"text-lg font-semibold text-zinc-300 mb-3\">")
				if err != nil {
					return err
				}
				var_33 := `Approved Topics`
				_, err = templBuffer.WriteString(var_33)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</h2> <div class=\"grid grid-cols-1 md:grid-cols-2 gap-3 mb-6\">")
				if err != nil {
					return err
				}
				for _, topic := range data.ApprovedTopics {
					_, err = templBuffer.WriteString("<div class=\"card p-4 border-green-500/30\"><h3 class=\"font-semibold text-zinc-100 text-sm\">")
					if err != nil {
						return err
					}
					var var_34 string = topic.Title
					_, err = templBuffer.WriteString(templ.EscapeString(var_34))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</h3><p class=\"text-zinc-400 text-xs mt-1\">")
					if err != nil {
						return err
					}
					var var_35 string = topic.Angle
					_, err = templBuffer.WriteString(templ.EscapeString(var_35))
					if err != nil {
						return err
					}
					_, err = templBuffer.WriteString("</p></div>")
					if err != nil {
						return err
					}
				}
				_, err = templBuffer.WriteString("</div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("<div class=\"flex flex-col gap-3\" id=\"topic-steps\">")
			if err != nil {
				return err
			}
			for _, step := range data.Steps {
				_, err = templBuffer.WriteString("<div class=\"step-card card\" data-step-id=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", step.ID)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" data-status=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(step.Status))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" data-step-type=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(step.StepType))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" data-round=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", step.Round)))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" data-tool-calls=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(step.ToolCalls))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" data-usage=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(step.Usage))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" data-output=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(step.Output))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\"></div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</div>")
			if err != nil {
				return err
			}
			if data.Status == "pending" && len(data.Steps) == 0 {
				_, err = templBuffer.WriteString("<div class=\"flex items-center gap-2 mt-4\"><button class=\"btn btn-primary\" id=\"run-topics-btn\">")
				if err != nil {
					return err
				}
				var_36 := `Run Topic Generator`
				_, err = templBuffer.WriteString(var_36)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button><button class=\"btn btn-danger hidden\" id=\"cancel-topics-btn\">")
				if err != nil {
					return err
				}
				var_37 := `Cancel`
				_, err = templBuffer.WriteString(var_37)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></div>")
				if err != nil {
					return err
				}
			}
			if data.Status == "failed" {
				_, err = templBuffer.WriteString("<div class=\"flex items-center gap-2 mt-4\"><form method=\"POST\" action=\"")
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString(templ.EscapeString(templ.SafeURL(fmt.Sprintf("/projects/%d/topics/%d/retry", data.ProjectID, data.RunID))))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("\" class=\"inline\"><button type=\"submit\" class=\"btn btn-primary\">")
				if err != nil {
					return err
				}
				var_38 := `Retry`
				_, err = templBuffer.WriteString(var_38)
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</button></form></div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</div> <script>")
			if err != nil {
				return err
			}
			var_39 := `
			(function() {
				var page = document.getElementById('topic-run-page');
				if (!page) return;

				var projectID = page.dataset.projectId;
				var runID = page.dataset.runId;
				var status = page.dataset.status;
				var stepsContainer = document.getElementById('topic-steps');
				var runBtn = document.getElementById('run-topics-btn');
				var cancelBtn = document.getElementById('cancel-topics-btn');

				// Render all existing step cards from data attributes
				StepCards.renderAll();

				var beforeUnloadHandler = function(e) {
					e.preventDefault();
				};

				var activeSource = null;

				function startStream() {
					if (runBtn) {
						runBtn.disabled = true;
						runBtn.textContent = 'Running...';
					}
					if (cancelBtn) cancelBtn.classList.remove('hidden');
					window.addEventListener('beforeunload', beforeUnloadHandler);

					var currentCard = null;
					var currentRefs = null;
					var source = new EventSource('/projects/' + projectID + '/topics/' + runID + '/stream');
					activeSource = source;

					source.onmessage = function(event) {
						var d = JSON.parse(event.data);

						if (d.type === 'step_start') {
							currentCard = StepCards.create(d.step_id, d.step_type, d.round, 'running');
							currentRefs = {
								tickerEl: currentCard.querySelector('.step-thinking-ticker'),
								streamEl: currentCard.querySelector('.step-stream'),
								pulseEl: currentCard.querySelector('.step-thinking-pulse'),
								badge: currentCard.querySelector('.badge')
							};
							if (currentRefs.pulseEl) currentRefs.pulseEl.classList.remove('hidden');
							stepsContainer.appendChild(currentCard);
						} else if (d.type === 'thinking' && currentRefs) {
							currentRefs.tickerEl.textContent += d.chunk;
							currentRefs.tickerEl.scrollTop = currentRefs.tickerEl.scrollHeight;
						} else if (d.type === 'chunk' && currentRefs) {
							currentRefs.streamEl.textContent += d.chunk;
							currentRefs.streamEl.scrollTop = currentRefs.streamEl.scrollHeight;
						} else if (d.type === 'step_done' && currentCard) {
							if (currentRefs.pulseEl) currentRefs.pulseEl.classList.add('hidden');
							currentRefs.tickerEl.classList.add('done');
							currentRefs.badge.textContent = d.status;
							currentRefs.badge.className = 'ml-auto badge ' + (d.status === 'completed' ? 'badge-completed' : 'badge-failed');
							currentCard.dataset.status = d.status;
							if (d.usage) StepCards.setUsage(currentCard, JSON.stringify(d.usage));
							currentCard = null;
							currentRefs = null;
						} else if (d.type === 'done') {
							source.close();
							activeSource = null;
							if (cancelBtn) cancelBtn.classList.add('hidden');
							window.removeEventListener('beforeunload', beforeUnloadHandler);
							window.location.reload();
						} else if (d.type === 'error') {
							source.close();
							activeSource = null;
							if (cancelBtn) cancelBtn.classList.add('hidden');
							window.removeEventListener('beforeunload', beforeUnloadHandler);
							if (currentRefs) {
								currentRefs.streamEl.textContent += '\nError: ' + d.error;
								currentRefs.badge.textContent = 'failed';
								currentRefs.badge.className = 'ml-auto badge badge-failed';
							}
						}
					};

					source.onerror = function() {
						source.close();
						activeSource = null;
						if (cancelBtn) cancelBtn.classList.add('hidden');
						window.removeEventListener('beforeunload', beforeUnloadHandler);
					};
				}

				if (cancelBtn) {
					cancelBtn.addEventListener('click', function() {
						if (activeSource) {
							activeSource.close();
							activeSource = null;
						}
						window.removeEventListener('beforeunload', beforeUnloadHandler);
						cancelBtn.classList.add('hidden');
						window.location.reload();
					});
				}

				// Auto-start if run is pending with no steps yet
				if (status === 'pending') {
					var existingSteps = stepsContainer.querySelectorAll('.step-card');
					if (existingSteps.length === 0) {
						startStream();
					}
				}

				if (runBtn) {
					runBtn.addEventListener('click', startStream);
				}
			})();
		`
			_, err = templBuffer.WriteString(var_39)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</script>")
			if err != nil {
				return err
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = components.ProjectPageShell("Topic Generation", []components.Breadcrumb{
			{Label: "Projects", URL: "/projects"},
			{Label: data.ProjectName, URL: fmt.Sprintf("/projects/%d", data.ProjectID)},
			{Label: "Topics", URL: fmt.Sprintf("/projects/%d/topics", data.ProjectID)},
			{Label: "Run"},
		}, data.ProjectID, data.ProjectName, "topics").Render(templ.WithChildren(ctx, var_25), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
